create database if not exists "todo_app";
set schema "todo_app";
drop table if exists "users";
create table "users" (
  "user_id" int not null generated by default as identity,
  "username" varchar(35) not null,
  "password" varchar(128) not null,
  "email" varchar(45) not null,
  unique ("user_id"),
  unique ("username"),
  unique ("email")
);
drop table if exists "tasks";
create table "tasks" (
  "task_id" int not null generated by default as identity,
  "date" date,
  "title" varchar(55) not null,
  "description" varchar(150) not null,
  "taskDone" tinyint not null default '0',
  "user_id" int not null,
  constraint "user_id"
    foreign key ("user_id")
    references "users" ("user_id")
);
drop table if exists "roles";
create table "roles" (
  "role_id" int not null generated by default as identity,
  "role" varchar(15) not null,
  "description" varchar(150) not null,
  "user_id" int not null,
  constraint "user_id_roles"
    foreign key ("user_id")
    references "users" ("user_id")
);
delete from roles where role_id = 1;
insert into roles(role, description) values ("ROLE_USER", "role for user");
